import { MeetingDTO, DecisionDTO, ActionItemDTO, FollowThroughDTO, OwnerDTO } from '@/types';

export const MOCK_OWNERS: OwnerDTO[] = [
  {
    id: 'owner-1',
    name: 'Priya Sharma',
    email: 'priya@meetrix.ai',
    avatarUrl: undefined,
  },
  {
    id: 'owner-2',
    name: 'Arjun Mehta',
    email: 'arjun@meetrix.ai',
    avatarUrl: undefined,
  },
  {
    id: 'owner-3',
    name: 'Kavya Nair (DevOps Lead)',
    email: 'kavya@meetrix.ai',
    avatarUrl: undefined,
  },
];

export const MOCK_MEETINGS: MeetingDTO[] = [
  {
    id: 'mtg-101',
    title: 'Sprint 14 Planning & DB Architecture',
    description: 'Migration from legacy MongoDB to PostgreSQL with Prisma ORM and multi-tenant schema isolation.',
    status: 'ANALYZED',
    scheduledAt: new Date(Date.now() - 6 * 24 * 60 * 60 * 1000).toISOString(),
    durationSeconds: 2400,
    audioUrl: 'https://actions.google.com/sounds/v1/ambiences/office_space.ogg',
    speakers: [
      { id: 'spk-1', speakerLabel: 'Speaker 0 (Priya)', ownerId: 'owner-1', owner: MOCK_OWNERS[0] },
      { id: 'spk-2', speakerLabel: 'Speaker 1 (Arjun)', ownerId: 'owner-2', owner: MOCK_OWNERS[1] },
    ],
    transcriptUtterances: [
      {
        id: 'utt-1',
        speakerLabel: 'Speaker 0 (Priya)',
        speakerName: 'Priya Sharma',
        startTime: 0,
        endTime: 12.4,
        sequence: 1,
        text: "Let's kick off Sprint 14. First agenda item: our database migration strategy. We decided last week to move to PostgreSQL using Prisma ORM.",
      },
      {
        id: 'utt-2',
        speakerLabel: 'Speaker 1 (Arjun)',
        speakerName: 'Arjun Mehta',
        startTime: 12.8,
        endTime: 28.5,
        sequence: 2,
        text: "Yes, I will handle the PostgreSQL schema implementation and make sure all tenant data is scoped by Organization ID.",
      },
      {
        id: 'utt-3',
        speakerLabel: 'Speaker 0 (Priya)',
        speakerName: 'Priya Sharma',
        startTime: 29.0,
        endTime: 45.2,
        sequence: 3,
        text: "Great. Second item: AI Speech-to-Text. We agreed to integrate the Whisper API and speaker diarization so task tickets get assigned to the right owner automatically.",
      },
      {
        id: 'utt-4',
        speakerLabel: 'Speaker 1 (Arjun)',
        speakerName: 'Arjun Mehta',
        startTime: 45.8,
        endTime: 62.0,
        sequence: 4,
        text: "Sounds good! I will prioritize the DB migration first, then hand off the Whisper integration to Priya by Thursday.",
      },
    ],
    decisions: [],
    actionItems: [],
  },
  {
    id: 'mtg-102',
    title: 'Weekly Standup & Follow-Through Review',
    description: 'Reviewing progress on previous sprint decisions and flagging stalled action items.',
    status: 'ANALYZED',
    scheduledAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
    durationSeconds: 1500,
    audioUrl: 'https://actions.google.com/sounds/v1/ambiences/office_space.ogg',
    speakers: [
      { id: 'spk-3', speakerLabel: 'Speaker 0 (Priya)', ownerId: 'owner-1', owner: MOCK_OWNERS[0] },
      { id: 'spk-4', speakerLabel: 'Speaker 1 (Arjun)', ownerId: 'owner-2', owner: MOCK_OWNERS[1] },
      { id: 'spk-5', speakerLabel: 'Speaker 2 (Kavya)', ownerId: 'owner-3', owner: MOCK_OWNERS[2] },
    ],
    transcriptUtterances: [
      {
        id: 'utt-5',
        speakerLabel: 'Speaker 0 (Priya)',
        speakerName: 'Priya Sharma',
        startTime: 0,
        endTime: 15.0,
        sequence: 1,
        text: "Welcome team. Arjun, how is the PostgreSQL schema work progressing?",
      },
      {
        id: 'utt-6',
        speakerLabel: 'Speaker 1 (Arjun)',
        speakerName: 'Arjun Mehta',
        startTime: 15.5,
        endTime: 30.0,
        sequence: 2,
        text: "The PostgreSQL schema is live with Prisma Client v5. All migrations passed cleanly in dev environment.",
      },
      {
        id: 'utt-7',
        speakerLabel: 'Speaker 0 (Priya)',
        speakerName: 'Priya Sharma',
        startTime: 30.5,
        endTime: 48.0,
        sequence: 3,
        text: "What about the Whisper API integration decision from Sprint 14? Has anyone started building the audio ingestion worker?",
      },
      {
        id: 'utt-8',
        speakerLabel: 'Speaker 1 (Arjun)',
        speakerName: 'Arjun Mehta',
        startTime: 48.5,
        endTime: 65.0,
        sequence: 4,
        text: "We haven't started that yet because we got blocked on S3 presigned URL permissions. It's currently unacted on.",
      },
    ],
    decisions: [],
    actionItems: [],
  },
  {
    id: 'mtg-103',
    title: 'Customer Onboarding & Feedback Sync',
    description: 'Processing recording from beta enterprise client feedback call.',
    status: 'PROCESSING',
    scheduledAt: new Date(Date.now() - 1 * 60 * 60 * 1000).toISOString(),
    durationSeconds: 1800,
    speakers: [],
    transcriptUtterances: [],
    decisions: [],
    actionItems: [],
  },
];

export const MOCK_DECISIONS: DecisionDTO[] = [
  {
    id: 'dec-1',
    originMeetingId: 'mtg-101',
    originMeetingTitle: 'Sprint 14 Planning & DB Architecture',
    title: 'Migrate core database to PostgreSQL + Prisma ORM',
    context: 'Evaluated MongoDB vs PostgreSQL for structural type safety and multi-tenant schema isolation.',
    rationale: 'PostgreSQL provides robust ACID compliance and relational links between decisions and action items.',
    status: 'FULFILLED',
    impactScore: 5,
    createdAt: new Date(Date.now() - 6 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
    actionItemsCount: 1,
    followThroughCount: 1,
  },
  {
    id: 'dec-2',
    originMeetingId: 'mtg-101',
    originMeetingTitle: 'Sprint 14 Planning & DB Architecture',
    title: 'Implement Whisper API + Speaker Diarization Ingestion Pipeline',
    context: 'Automate speech-to-text transcript processing with automatic speaker attribution to eliminate manual meeting notes.',
    rationale: 'Saves 4+ hours per week of manual notes and ensures action item accountability.',
    status: 'UNACTED_ALERT',
    impactScore: 4,
    createdAt: new Date(Date.now() - 6 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
    actionItemsCount: 1,
    followThroughCount: 1,
    latestFollowThrough: {
      id: 'ft-101',
      decisionId: 'dec-2',
      decisionTitle: 'Implement Whisper API + Speaker Diarization Ingestion Pipeline',
      reviewMeetingId: 'mtg-102',
      reviewMeetingTitle: 'Weekly Standup & Follow-Through Review',
      statusAtReview: 'UNACTED_ALERT',
      evidenceText: 'Transcript analysis indicates no mention of Whisper API integration work or active PRs in Meeting 102.',
      confidenceScore: 0.94,
      flaggedUnacted: true,
      createdAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
    },
  },
  {
    id: 'dec-3',
    originMeetingId: 'mtg-102',
    originMeetingTitle: 'Weekly Standup & Follow-Through Review',
    title: 'Integrate Slack & Jira Webhooks for Ticket Auto-Dispatch',
    context: 'Automatically dispatch extracted action items directly to team Jira backlogs and send Slack notifications.',
    rationale: 'Reduces context switching and prevents tickets from being forgotten.',
    status: 'ACTIVE',
    impactScore: 3,
    createdAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
    actionItemsCount: 1,
    followThroughCount: 0,
  },
];

export const MOCK_ACTION_ITEMS: ActionItemDTO[] = [
  {
    id: 'act-1',
    meetingId: 'mtg-101',
    meetingTitle: 'Sprint 14 Planning & DB Architecture',
    decisionId: 'dec-1',
    decisionTitle: 'Migrate core database to PostgreSQL + Prisma ORM',
    title: 'Setup PostgreSQL schema & Prisma Client integration',
    description: 'Configure Prisma schema models for Org, User, Meeting, and TranscriptUtterance.',
    status: 'COMPLETED',
    priority: 'HIGH',
    assigneeName: 'Arjun Mehta',
    assigneeAvatar: undefined,
    ownerId: 'owner-2',
    dueDate: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
    createdAt: new Date(Date.now() - 6 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'act-2',
    meetingId: 'mtg-101',
    meetingTitle: 'Sprint 14 Planning & DB Architecture',
    decisionId: 'dec-2',
    decisionTitle: 'Implement Whisper API + Speaker Diarization Ingestion Pipeline',
    title: 'Build Whisper API Ingestion Worker',
    description: 'Integrate audio upload endpoint and async transcription pipeline.',
    status: 'OPEN',
    priority: 'URGENT',
    assigneeName: 'Priya Sharma',
    assigneeAvatar: undefined,
    ownerId: 'owner-1',
    dueDate: new Date(Date.now() + 3 * 24 * 60 * 60 * 1000).toISOString(),
    createdAt: new Date(Date.now() - 6 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: 'act-3',
    meetingId: 'mtg-102',
    meetingTitle: 'Weekly Standup & Follow-Through Review',
    decisionId: 'dec-3',
    decisionTitle: 'Integrate Slack & Jira Webhooks for Ticket Auto-Dispatch',
    title: 'Configure Jira OAuth2 & Slack Webhook API router',
    description: 'Build backend API routes in /src/app/api/export/jira for payload transformation.',
    status: 'IN_PROGRESS',
    priority: 'MEDIUM',
    assigneeName: 'Kavya Nair',
    assigneeAvatar: undefined,
    ownerId: 'owner-3',
    dueDate: new Date(Date.now() + 5 * 24 * 60 * 60 * 1000).toISOString(),
    createdAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
  },
];
