import { NextRequest, NextResponse } from 'next/server';
import { prisma } from '@/lib/db/prisma';
import { decryptText } from '@/lib/crypto';
import { z } from 'zod';

const JiraExportSchema = z.object({
  actionItemId: z.string().optional(),
  title: z.string().min(1, 'Title required'),
  description: z.string().optional(),
  priority: z.string().optional().default('MEDIUM'),
  assigneeName: z.string().optional(),
  projectKey: z.string().optional().default('ENG'),
});

export async function POST(req: NextRequest) {
  try {
    const body = await req.json();
    const validation = JiraExportSchema.safeParse(body);

    if (!validation.success) {
      return NextResponse.json(
        { error: 'Invalid Jira payload', details: validation.error.flatten().fieldErrors },
        { status: 400 }
      );
    }

    const { actionItemId, title, description, priority, assigneeName, projectKey } = validation.data;

    // Fetch and decrypt stored Jira integration credentials from DB
    let hostUrl: string | null = null;
    let userEmail: string | null = null;
    let apiToken: string | null = null;

    const org = await prisma.organization.findFirst();
    if (org) {
      const setting = await prisma.integrationSetting.findUnique({
        where: { organizationId_provider: { organizationId: org.id, provider: 'JIRA' } },
      });

      hostUrl = decryptText(setting?.encryptedHostUrl);
      userEmail = decryptText(setting?.encryptedUserEmail);
      apiToken = decryptText(setting?.encryptedApiToken);
    }

    // Fallback simulation if no live Jira token is configured
    if (!hostUrl || !apiToken || !userEmail) {
      console.log('[Jira Sync] No decrypted Jira API token found in DB. Simulating Jira issue creation...');
      const ticketKey = `${projectKey}-${Math.floor(1000 + Math.random() * 9000)}`;

      return NextResponse.json({
        success: true,
        isSimulated: true,
        ticketKey,
        ticketUrl: `https://meetrix-workspace.atlassian.net/browse/${ticketKey}`,
        message: `Simulated Jira ticket ${ticketKey}. Configure Jira API token in Settings to sync live tickets.`,
      });
    }

    // Live HTTP request to Atlassian Jira Cloud REST API v3
    const cleanHost = hostUrl.replace(/\/$/, '');
    const authHeader = Buffer.from(`${userEmail}:${apiToken}`).toString('base64');

    const jiraPayload = {
      fields: {
        project: { key: projectKey },
        summary: title,
        description: {
          type: 'doc',
          version: 1,
          content: [
            {
              type: 'paragraph',
              content: [
                {
                  type: 'text',
                  text: description || 'Action item generated by AI Meeting Engine.',
                },
              ],
            },
          ],
        },
        issuetype: { name: 'Task' },
      },
    };

    const res = await fetch(`${cleanHost}/rest/api/3/issue`, {
      method: 'POST',
      headers: {
        Authorization: `Basic ${authHeader}`,
        'Content-Type': 'application/json',
        Accept: 'application/json',
      },
      body: JSON.stringify(jiraPayload),
    });

    if (!res.ok) {
      const errText = await res.text();
      console.error('[Jira API Error]:', errText);
      throw new Error(`Jira API HTTP ${res.status}: ${errText}`);
    }

    const jiraResponse = await res.json();
    const createdKey = jiraResponse.key;
    const ticketUrl = `${cleanHost}/browse/${createdKey}`;

    return NextResponse.json({
      success: true,
      isSimulated: false,
      ticketKey: createdKey,
      ticketUrl,
      message: `Jira ticket ${createdKey} created successfully!`,
    });
  } catch (error: any) {
    console.error('[API POST /api/export/jira] Error:', error);
    return NextResponse.json({ error: 'Failed to create Jira ticket', message: error.message }, { status: 500 });
  }
}
